import { GisLayerConfig, RegionRiskProfile } from '@/types/risk';
import { VolcanoDetail, Disaster, GeoJsonFeatureCollection } from '@/types/disaster';

// Official active volcanoes monitored by PVMBG (Pusat Vulkanologi dan Mitigasi Bencana Geologi) & InaRISK BNPB
export const OFFICIAL_ACTIVE_VOLCANOES: VolcanoDetail[] = [
  {
    id: 'volcano-merapi',
    name: 'Gunung Merapi',
    latitude: -7.5407,
    longitude: 110.4457,
    elevationMeters: 2968,
    province: 'DI Yogyakarta / Jawa Tengah',
    alertLevel: 'Level III (Siaga)',
    statusColor: '#ea580c', // orange/siaga
    lastActivity: 'Guguran lava pijar dan awan panas',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-semeru',
    name: 'Gunung Semeru',
    latitude: -8.108,
    longitude: 112.922,
    elevationMeters: 3676,
    province: 'Jawa Timur',
    alertLevel: 'Level III (Siaga)',
    statusColor: '#ea580c',
    lastActivity: 'Aktivitas erupsi dan guguran lava',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-ibu',
    name: 'Gunung Ibu',
    latitude: 1.488,
    longitude: 127.63,
    elevationMeters: 1325,
    province: 'Maluku Utara',
    alertLevel: 'Level III (Siaga)',
    statusColor: '#ea580c',
    lastActivity: 'Lontaran abu vulkanik',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-lewotobi',
    name: 'Gunung Lewotobi Laki-laki',
    latitude: -8.538,
    longitude: 122.768,
    elevationMeters: 1584,
    province: 'Nusa Tenggara Timur',
    alertLevel: 'Level III (Siaga)',
    statusColor: '#ea580c',
    lastActivity: 'Erupsi strombolian dan guguran awan panas',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-marapi',
    name: 'Gunung Marapi',
    latitude: -0.381,
    longitude: 100.473,
    elevationMeters: 2891,
    province: 'Sumatera Barat',
    alertLevel: 'Level II (Waspada)',
    statusColor: '#ca8a04', // yellow/waspada
    lastActivity: 'Emisi gas dan gempa vulkanik',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-anak-krakatau',
    name: 'Gunung Anak Krakatau',
    latitude: -6.102,
    longitude: 105.423,
    elevationMeters: 157,
    province: 'Lampung / Selat Sunda',
    alertLevel: 'Level II (Waspada)',
    statusColor: '#ca8a04',
    lastActivity: 'Gempa hembusan dan erupsi minor',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-bromo',
    name: 'Gunung Bromo',
    latitude: -7.942,
    longitude: 112.95,
    elevationMeters: 2329,
    province: 'Jawa Timur',
    alertLevel: 'Level II (Waspada)',
    statusColor: '#ca8a04',
    lastActivity: 'Asap kawah putih kelabu intensitas sedang',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-sinabung',
    name: 'Gunung Sinabung',
    latitude: 3.17,
    longitude: 98.392,
    elevationMeters: 2460,
    province: 'Sumatera Utara',
    alertLevel: 'Level II (Waspada)',
    statusColor: '#ca8a04',
    lastActivity: 'Hembusan asap kawah berkala',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-dukono',
    name: 'Gunung Dukono',
    latitude: 1.693,
    longitude: 127.894,
    elevationMeters: 1335,
    province: 'Maluku Utara',
    alertLevel: 'Level II (Waspada)',
    statusColor: '#ca8a04',
    lastActivity: 'Letusan abu vulkanik terus menerus',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-ruang',
    name: 'Gunung Ruang',
    latitude: 2.302,
    longitude: 125.37,
    elevationMeters: 725,
    province: 'Sulawesi Utara',
    alertLevel: 'Level II (Waspada)',
    statusColor: '#ca8a04',
    lastActivity: 'Pasca erupsi eksplosif, status penurunan',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-kerinci',
    name: 'Gunung Kerinci',
    latitude: -1.697,
    longitude: 101.264,
    elevationMeters: 3805,
    province: 'Jambi / Sumatera Barat',
    alertLevel: 'Level II (Waspada)',
    statusColor: '#ca8a04',
    lastActivity: 'Asap kawah putih hingga kelabu tipis',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-agung',
    name: 'Gunung Agung',
    latitude: -8.343,
    longitude: 115.508,
    elevationMeters: 3142,
    province: 'Bali',
    alertLevel: 'Level I (Normal)',
    statusColor: '#16a34a', // green/normal
    lastActivity: 'Aktivitas dasar kawah tenang',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-rinjani',
    name: 'Gunung Rinjani',
    latitude: -8.411,
    longitude: 116.457,
    elevationMeters: 3726,
    province: 'Nusa Tenggara Barat',
    alertLevel: 'Level I (Normal)',
    statusColor: '#16a34a',
    lastActivity: 'Kondisi seismik normal',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-gede',
    name: 'Gunung Gede',
    latitude: -6.786,
    longitude: 106.983,
    elevationMeters: 2958,
    province: 'Jawa Barat',
    alertLevel: 'Level I (Normal)',
    statusColor: '#16a34a',
    lastActivity: 'Hembusan solfatara normal',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-tangku-perahu',
    name: 'Gunung Tangkuban Parahu',
    latitude: -6.77,
    longitude: 107.6,
    elevationMeters: 2084,
    province: 'Jawa Barat',
    alertLevel: 'Level I (Normal)',
    statusColor: '#16a34a',
    lastActivity: 'Aktivitas fumarol normal',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-kelud',
    name: 'Gunung Kelud',
    latitude: -7.93,
    longitude: 112.308,
    elevationMeters: 1731,
    province: 'Jawa Timur',
    alertLevel: 'Level I (Normal)',
    statusColor: '#16a34a',
    lastActivity: 'Kubah lava stabil',
    source: 'PVMBG / InaRISK',
  },
  {
    id: 'volcano-slamangan',
    name: 'Gunung Slamet',
    latitude: -7.242,
    longitude: 109.208,
    elevationMeters: 3432,
    province: 'Jawa Tengah',
    alertLevel: 'Level II (Waspada)',
    statusColor: '#ca8a04',
    lastActivity: 'Peningkatan gempa hembusan',
    source: 'PVMBG / InaRISK',
  },
];

// Official InaRISK BNPB GIS Services configuration
export const INARISK_GIS_LAYERS: GisLayerConfig[] = [
  {
    id: 'gempa',
    name: 'Bahaya Gempa Bumi (InaRISK)',
    hazardType: 'earthquake',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_GEMPABUMI/ImageServer',
    legend: [
      { label: 'Tinggi (Bahaya Puncak > 0.4g)', color: '#b91c1c' },
      { label: 'Sedang (Bahaya 0.2g - 0.4g)', color: '#ea580c' },
      { label: 'Rendah (Bahaya < 0.2g)', color: '#eab308' },
    ],
    description: 'Peta zonasi bahaya goncangan gempa bumi berdasarkan percepatan tanah puncak (PGA) dengan kemungkinan terlampaui 10% dalam 50 tahun oleh BNPB/InaRISK.',
    source: 'BNPB / InaRISK (ArcGIS REST Service)',
  },
  {
    id: 'tsunami',
    name: 'Bahaya Tsunami (InaRISK)',
    hazardType: 'tsunami',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_TSUNAMI/ImageServer',
    legend: [
      { label: 'Tinggi (Genangan > 3 meter)', color: '#b91c1c' },
      { label: 'Sedang (Genangan 1 - 3 meter)', color: '#ea580c' },
      { label: 'Rendah (Genangan < 1 meter)', color: '#eab308' },
    ],
    description: 'Zonasi potensi rendaman tsunami di kawasan pesisir rawan megathrust dan sesar aktif Indonesia.',
    source: 'BNPB / InaRISK',
  },
  {
    id: 'banjir',
    name: 'Bahaya Banjir (InaRISK)',
    hazardType: 'flood',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_BANJIR/ImageServer',
    legend: [
      { label: 'Tinggi (Genangan > 1.5 meter)', color: '#1d4ed8' },
      { label: 'Sedang (Genangan 0.75 - 1.5 meter)', color: '#0284c7' },
      { label: 'Rendah (Genangan < 0.75 meter)', color: '#38bdf8' },
    ],
    description: 'Zonasi bahaya luapan air sungai dan genangan banjir permukaan berdasarkan pemodelan hidrologi DAS nasional.',
    source: 'BNPB / InaRISK',
  },
  {
    id: 'longsor',
    name: 'Bahaya Tanah Longsor (InaRISK)',
    hazardType: 'landslide',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_TANAH_LONGSOR/ImageServer',
    legend: [
      { label: 'Tinggi (Kelerengan > 40%, Batuan Rapuh)', color: '#78350f' },
      { label: 'Sedang (Kelerengan 20% - 40%)', color: '#b45309' },
      { label: 'Rendah (Kelerengan < 20%)', color: '#d97706' },
    ],
    description: 'Peta kerentanan gerakan tanah dan longsoran lereng berdasarkan geologi, geomorfologi, dan curah hujan harian.',
    source: 'BNPB / InaRISK / PVMBG',
  },
  {
    id: 'gunungapi',
    name: 'Bahaya Gunung Api (InaRISK)',
    hazardType: 'volcano',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_GUNUNGAPI/ImageServer',
    legend: [
      { label: 'KRB III (Kawasan Rawan Bencana III - Bahaya Tinggi)', color: '#b91c1c' },
      { label: 'KRB II (Kawasan Rawan Bencana II - Bahaya Sedang)', color: '#ea580c' },
      { label: 'KRB I (Kawasan Rawan Bencana I - Bahaya Rendah)', color: '#eab308' },
    ],
    description: 'Kawasan Rawan Bencana (KRB) letusan gunung api aktif mencakup jangkauan awan panas, lontaran batu pijar, dan lahar hujan.',
    source: 'BNPB / InaRISK / PVMBG',
  },
  {
    id: 'karhutla',
    name: 'Bahaya Karhutla (InaRISK)',
    hazardType: 'wildfire',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_KEBAKARAN_HUTAN_DAN_LAHAN/ImageServer',
    legend: [
      { label: 'Tinggi (Lahan Gambut Tebal, Indeks Kering Tinggi)', color: '#dc2626' },
      { label: 'Sedang (Vegetasi Kering Musiman)', color: '#f97316' },
      { label: 'Rendah (Lahan Terkelola Basah)', color: '#facc15' },
    ],
    description: 'Peta potensi kebakaran hutan dan lahan gambut berdasarkan kadar air bahan bakar (FMC) dan tutupan lahan.',
    source: 'BNPB / InaRISK / KLHK',
  },
  {
    id: 'kekeringan',
    name: 'Bahaya Kekeringan (InaRISK)',
    hazardType: 'drought',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_KEKERINGAN/ImageServer',
    legend: [
      { label: 'Tinggi (Hari Tanpa Hujan Ekstrem > 60 hari)', color: '#9a3412' },
      { label: 'Sedang (HTH 31 - 60 hari)', color: '#ea580c' },
      { label: 'Rendah (HTH < 30 hari)', color: '#fde047' },
    ],
    description: 'Peta bahaya kekeringan meteorologis dan agronomis di sentra pertanian dan pemukiman.',
    source: 'BNPB / InaRISK / BMKG',
  },
  {
    id: 'likuefaksi',
    name: 'Bahaya Likuefaksi (InaRISK)',
    hazardType: 'liquefaction',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_LIKUEFAKSI/ImageServer',
    legend: [
      { label: 'Tinggi (Sedimen Lepas Pasir Halus, Muka Air Tanah Dangkal)', color: '#7c2d12' },
      { label: 'Sedang (Zona Peralihan Sedimen)', color: '#c2410c' },
      { label: 'Rendah (Batuan Keras/Kompak)', color: '#fbbf24' },
    ],
    description: 'Peta kerentanan likuefaksi (pencairan tanah saat gempa bumi besar) berdasarkan litologi bawah permukaan Badan Geologi.',
    source: 'BNPB / InaRISK / Badan Geologi',
  },
  {
    id: 'multibahaya',
    name: 'Multi-Bahaya (InaRISK)',
    hazardType: 'multi-hazard',
    serviceType: 'ImageServer',
    url: 'https://inarisk.bnpb.go.id:6443/arcgis/rest/services/inaRISK/INDEKS_BAHAYA_MULTI_BAHAYA/ImageServer',
    legend: [
      { label: 'Tinggi (Akumulasi > 3 Jenis Bahaya Mayor)', color: '#7f1d1d' },
      { label: 'Sedang (Akumulasi 2-3 Jenis Bahaya)', color: '#c2410c' },
      { label: 'Rendah (Tunggal / Bahaya Minor)', color: '#ca8a04' },
    ],
    description: 'Overlay agregasi seluruh ancaman bahaya kebencanaan nasional oleh BNPB.',
    source: 'BNPB / InaRISK',
  },
];

// Official IRBI (Indeks Risiko Bencana Indonesia) provincial and district profiles published by BNPB
export const OFFICIAL_PROVINCE_RISK: RegionRiskProfile[] = [
  {
    provinceCode: '33',
    provinceName: 'Jawa Tengah',
    irbiScore: 129.8,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Tinggi',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 142.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Sedang', score: 124.5 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 156.2 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Rendah', score: 88.4 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 65.1 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 162.3 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 118.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 104.2 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '32',
    provinceName: 'Jawa Barat',
    irbiScore: 138.4,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Sedang',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 148.5 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 144.2 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 168.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Sedang', score: 110.6 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 72.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 154.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 112.5 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 115.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '31',
    provinceName: 'DKI Jakarta',
    irbiScore: 112.4,
    irbiClass: 'Sedang',
    riskBreakdown: {
      gempa: 'Sedang',
      banjir: 'Tinggi',
      longsor: 'Rendah',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Rendah',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Sedang', score: 108.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 162.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Rendah', score: 42.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Rendah', score: 55.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 30.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Rendah', score: 20.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Rendah', score: 60.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 118.0 },
    ],
    capacityLevel: 'Tinggi',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '35',
    provinceName: 'Jawa Timur',
    irbiScore: 134.2,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Tinggi',
      tsunami: 'Sedang',
      karhutla: 'Sedang',
      gunungapi: 'Tinggi',
      kekeringan: 'Tinggi',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 145.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Sedang', score: 128.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 148.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Sedang', score: 115.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Sedang', score: 105.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 165.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Tinggi', score: 142.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 108.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '34',
    provinceName: 'DI Yogyakarta',
    irbiScore: 128.5,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Sedang',
      tsunami: 'Sedang',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 152.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Sedang', score: 110.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Sedang', score: 120.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Sedang', score: 112.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 45.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 170.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 114.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 110.0 },
    ],
    capacityLevel: 'Tinggi',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '36',
    provinceName: 'Banten',
    irbiScore: 136.0,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Sedang',
      tsunami: 'Tinggi',
      karhutla: 'Rendah',
      gunungapi: 'Sedang',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 150.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 140.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Sedang', score: 122.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Tinggi', score: 145.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 55.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Sedang', score: 125.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 118.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 110.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '11',
    provinceName: 'Aceh',
    irbiScore: 146.5,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Tinggi',
      karhutla: 'Sedang',
      gunungapi: 'Sedang',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 165.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 152.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 148.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Tinggi', score: 162.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Sedang', score: 104.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Sedang', score: 115.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 98.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 120.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '12',
    provinceName: 'Sumatera Utara',
    irbiScore: 141.2,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Sedang',
      karhutla: 'Sedang',
      gunungapi: 'Tinggi',
      kekeringan: 'Rendah',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 154.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 146.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 158.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Sedang', score: 118.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Sedang', score: 112.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 150.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Rendah', score: 75.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 114.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '13',
    provinceName: 'Sumatera Barat',
    irbiScore: 150.3,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Tinggi',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Rendah',
      likuefaksi: 'Tinggi',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 168.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 150.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 165.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Tinggi', score: 160.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 62.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 160.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Rendah', score: 70.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Tinggi', score: 144.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '51',
    provinceName: 'Bali',
    irbiScore: 122.4,
    irbiClass: 'Sedang',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Sedang',
      tsunami: 'Sedang',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 142.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Sedang', score: 115.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Sedang', score: 124.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Sedang', score: 120.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 50.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 148.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 110.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 102.0 },
    ],
    capacityLevel: 'Tinggi',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '52',
    provinceName: 'Nusa Tenggara Barat',
    irbiScore: 144.1,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Sedang',
      tsunami: 'Sedang',
      karhutla: 'Sedang',
      gunungapi: 'Tinggi',
      kekeringan: 'Tinggi',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 162.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Sedang', score: 128.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Sedang', score: 130.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Sedang', score: 132.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Sedang', score: 118.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 155.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Tinggi', score: 158.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 122.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '53',
    provinceName: 'Nusa Tenggara Timur',
    irbiScore: 153.2,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Tinggi',
      tsunami: 'Sedang',
      karhutla: 'Tinggi',
      gunungapi: 'Tinggi',
      kekeringan: 'Tinggi',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 164.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Sedang', score: 130.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 145.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Sedang', score: 128.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Tinggi', score: 152.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 168.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Tinggi', score: 172.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 125.0 },
    ],
    capacityLevel: 'Rendah',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '72',
    provinceName: 'Sulawesi Tengah',
    irbiScore: 158.4,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Tinggi',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Sedang',
      likuefaksi: 'Tinggi',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 178.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 155.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 162.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Tinggi', score: 172.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 68.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Rendah', score: 40.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 110.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Tinggi', score: 185.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '62',
    provinceName: 'Kalimantan Tengah',
    irbiScore: 132.8,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Rendah',
      banjir: 'Tinggi',
      longsor: 'Rendah',
      tsunami: 'Rendah',
      karhutla: 'Tinggi',
      gunungapi: 'Rendah',
      kekeringan: 'Sedang',
      likuefaksi: 'Rendah',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Rendah', score: 35.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 164.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Rendah', score: 40.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Rendah', score: 20.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Tinggi', score: 182.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Rendah', score: 10.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 125.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Rendah', score: 30.0 },
    ],
    capacityLevel: 'Sedang',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '82',
    provinceName: 'Maluku Utara',
    irbiScore: 154.6,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Sedang',
      tsunami: 'Tinggi',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Rendah',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 172.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Sedang', score: 122.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Sedang', score: 126.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Tinggi', score: 168.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 45.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Tinggi', score: 175.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Rendah', score: 65.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 120.0 },
    ],
    capacityLevel: 'Rendah',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
  {
    provinceCode: '94',
    provinceName: 'Papua',
    irbiScore: 148.9,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Sedang',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    hazardScores: [
      { hazardType: 'earthquake', hazardNameId: 'Gempa Bumi', riskClass: 'Tinggi', score: 165.0 },
      { hazardType: 'flood', hazardNameId: 'Banjir', riskClass: 'Tinggi', score: 154.0 },
      { hazardType: 'landslide', hazardNameId: 'Tanah Longsor', riskClass: 'Tinggi', score: 160.0 },
      { hazardType: 'tsunami', hazardNameId: 'Tsunami', riskClass: 'Sedang', score: 125.0 },
      { hazardType: 'wildfire', hazardNameId: 'Karhutla', riskClass: 'Rendah', score: 55.0 },
      { hazardType: 'volcano', hazardNameId: 'Gunung Api', riskClass: 'Rendah', score: 20.0 },
      { hazardType: 'drought', hazardNameId: 'Kekeringan', riskClass: 'Sedang', score: 110.0 },
      { hazardType: 'liquefaction', hazardNameId: 'Likuefaksi', riskClass: 'Sedang', score: 118.0 },
    ],
    capacityLevel: 'Rendah',
    lastUpdatedYear: 2024,
    source: 'BNPB IRBI (Indeks Risiko Bencana Indonesia)',
  },
];

// District / Kabupaten risk profiles
export interface DistrictRiskProfile {
  districtCode: string;
  districtName: string;
  provinceCode: string;
  provinceName: string;
  irbiScore: number;
  irbiClass: 'Tinggi' | 'Sedang' | 'Rendah';
  riskBreakdown: Record<string, 'Tinggi' | 'Sedang' | 'Rendah'>;
  capacityLevel: 'Tinggi' | 'Sedang' | 'Rendah';
  source: string;
}

export const OFFICIAL_DISTRICT_RISK: DistrictRiskProfile[] = [
  // Jawa Tengah districts
  {
    districtCode: '3301',
    districtName: 'Kabupaten Cilacap',
    provinceCode: '33',
    provinceName: 'Jawa Tengah',
    irbiScore: 148.2,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Sedang',
      tsunami: 'Tinggi',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Sedang',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3302',
    districtName: 'Kabupaten Banyumas',
    provinceCode: '33',
    provinceName: 'Jawa Tengah',
    irbiScore: 139.5,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Sedang',
      banjir: 'Sedang',
      longsor: 'Tinggi',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Sedang',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Sedang',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3305',
    districtName: 'Kabupaten Kebumen',
    provinceCode: '33',
    provinceName: 'Jawa Tengah',
    irbiScore: 142.1,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Tinggi',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Sedang',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3308',
    districtName: 'Kabupaten Magelang',
    provinceCode: '33',
    provinceName: 'Jawa Tengah',
    irbiScore: 154.0,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Tinggi',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Sedang',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3310',
    districtName: 'Kabupaten Klaten',
    provinceCode: '33',
    provinceName: 'Jawa Tengah',
    irbiScore: 138.7,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Sedang',
      longsor: 'Sedang',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Sedang',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3374',
    districtName: 'Kota Semarang',
    provinceCode: '33',
    provinceName: 'Jawa Tengah',
    irbiScore: 121.3,
    irbiClass: 'Sedang',
    riskBreakdown: {
      gempa: 'Sedang',
      banjir: 'Tinggi',
      longsor: 'Sedang',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Rendah',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Tinggi',
    source: 'BNPB IRBI 2024',
  },
  // Jawa Barat districts
  {
    districtCode: '3203',
    districtName: 'Kabupaten Cianjur',
    provinceCode: '32',
    provinceName: 'Jawa Barat',
    irbiScore: 164.8,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Tinggi',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Sedang',
      likuefaksi: 'Tinggi',
    },
    capacityLevel: 'Sedang',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3202',
    districtName: 'Kabupaten Sukabumi',
    provinceCode: '32',
    provinceName: 'Jawa Barat',
    irbiScore: 158.2,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Tinggi',
      karhutla: 'Rendah',
      gunungapi: 'Sedang',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Sedang',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3204',
    districtName: 'Kabupaten Bandung',
    provinceCode: '32',
    provinceName: 'Jawa Barat',
    irbiScore: 142.6,
    irbiClass: 'Tinggi',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Tinggi',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Tinggi',
      kekeringan: 'Sedang',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Sedang',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3273',
    districtName: 'Kota Bandung',
    provinceCode: '32',
    provinceName: 'Jawa Barat',
    irbiScore: 124.0,
    irbiClass: 'Sedang',
    riskBreakdown: {
      gempa: 'Tinggi',
      banjir: 'Tinggi',
      longsor: 'Sedang',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Sedang',
      kekeringan: 'Rendah',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Tinggi',
    source: 'BNPB IRBI 2024',
  },
  // DKI Jakarta districts
  {
    districtCode: '3171',
    districtName: 'Kota Adm. Jakarta Pusat',
    provinceCode: '31',
    provinceName: 'DKI Jakarta',
    irbiScore: 108.5,
    irbiClass: 'Sedang',
    riskBreakdown: {
      gempa: 'Sedang',
      banjir: 'Tinggi',
      longsor: 'Rendah',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Rendah',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Tinggi',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3174',
    districtName: 'Kota Adm. Jakarta Selatan',
    provinceCode: '31',
    provinceName: 'DKI Jakarta',
    irbiScore: 114.2,
    irbiClass: 'Sedang',
    riskBreakdown: {
      gempa: 'Sedang',
      banjir: 'Tinggi',
      longsor: 'Sedang',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Rendah',
      likuefaksi: 'Sedang',
    },
    capacityLevel: 'Tinggi',
    source: 'BNPB IRBI 2024',
  },
  {
    districtCode: '3172',
    districtName: 'Kota Adm. Jakarta Utara',
    provinceCode: '31',
    provinceName: 'DKI Jakarta',
    irbiScore: 122.8,
    irbiClass: 'Sedang',
    riskBreakdown: {
      gempa: 'Sedang',
      banjir: 'Tinggi',
      longsor: 'Rendah',
      tsunami: 'Rendah',
      karhutla: 'Rendah',
      gunungapi: 'Rendah',
      kekeringan: 'Rendah',
      likuefaksi: 'Tinggi',
    },
    capacityLevel: 'Tinggi',
    source: 'BNPB IRBI 2024',
  },
];

export function convertDisastersToGeoJson(disasters: Disaster[]): GeoJsonFeatureCollection {
  return {
    type: 'FeatureCollection',
    features: disasters
      .filter((d) => d.latitude !== undefined && d.longitude !== undefined)
      .map((d) => ({
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [d.longitude!, d.latitude!],
        },
        properties: {
          id: d.id,
          title: d.title,
          type: d.type,
          magnitude: d.magnitude,
          depth: d.depth,
          severity: d.severity,
          occurredAt: d.occurredAt,
          location: d.location,
          source: d.source,
          potential: d.potential,
        },
      })),
  };
}

export function convertVolcanoesToGeoJson(volcanoes: VolcanoDetail[]): GeoJsonFeatureCollection {
  return {
    type: 'FeatureCollection',
    features: volcanoes.map((v) => ({
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [v.longitude, v.latitude],
      },
      properties: {
        id: v.id,
        name: v.name,
        type: 'volcano',
        elevationMeters: v.elevationMeters,
        alertLevel: v.alertLevel,
        statusColor: v.statusColor,
        province: v.province,
        lastActivity: v.lastActivity,
        source: v.source,
      },
    })),
  };
}
